### ISSUE TITLE
create artwork works fine but toArtwork function report error

### ISSUE THREAD

**Issue by ZaynJarvis** [ntuoss/hackoss#13]
```bash
artworks.repository.js:157 Uncaught (in promise) TypeError: Cannot read property 'assign' of undefined
    at ArtworksRepository.<anonymous> (artworks.repository.js:157)
    at step (tslib.es6.js:197)
    at Object.next (tslib.es6.js:127)
    at tslib.es6.js:100
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.js:77)
    at ArtworksRepository.toArtwork (artworks.repository.js:150)
    at artworks.repository.js:121
    at Array.map (<anonymous>)
    at ArtworksRepository.<anonymous> (artworks.repository.js:120)
    at step (tslib.es6.js:197)
    at Object.next (tslib.es6.js:127)
    at fulfilled (tslib.es6.js:80)
```

**Comment by ZaynJarvis** [comment]
```js
    async getArtworks(
        filters: QueryFilter[] = [],
        limit: number = 10,
        orderBy: ArtworksOrderKey = 'title',
        direction: firebase.firestore.OrderByDirection = 'asc'
    ): Promise<Artwork[]> {
        const orderByPath = ARTWORKS_ORDER_KEY_PATH_MAP[orderBy];
        const results = await buildQuery(this.artworks, limit, orderByPath, direction, filters).get();
        return Promise.all(results.docs.map(doc => this.toArtwork(withId<FirebaseArtwork>(doc.data(), doc.id))));
    }

    async getArtwork(id: string): Promise<Artwork> {
        const ref = this.artworks.doc(id);
        const doc = await ref.get();
        return this.toArtwork(withId<FirebaseArtwork>(doc.data(), id));
    }

    private async toArtwork(data: FirebaseArtwork): Promise<Artwork> {
        const artist = this.peopleRepository.getPerson(data.artist.id);
        return _.assign(data, {
            artist: await artist
        });
    }
```
Here is the issue, when using `toArtwork` the value of `data` is a string (or reference). It's not an object and does not have `id` field.
Hence, when fetching data from artworks there are runtime error saying `Uncaught (in promise) TypeError: Cannot read property 'getPerson' of undefined`
Same error would expected to happen in eventRepo

**Comment by clarencecastillo** [comment]
> ```shell
> artworks.repository.js:157 Uncaught (in promise) TypeError: Cannot read property 'assign' of undefined
>     at ArtworksRepository.<anonymous> (artworks.repository.js:157)
>     at step (tslib.es6.js:197)
>     at Object.next (tslib.es6.js:127)
>     at tslib.es6.js:100
>     at new Promise (<anonymous>)
>     at Module.__awaiter (tslib.es6.js:77)
>     at ArtworksRepository.toArtwork (artworks.repository.js:150)
>     at artworks.repository.js:121
>     at Array.map (<anonymous>)
>     at ArtworksRepository.<anonymous> (artworks.repository.js:120)
>     at step (tslib.es6.js:197)
>     at Object.next (tslib.es6.js:127)
>     at fulfilled (tslib.es6.js:80)
> ```

Is it not because you don't have lodash installed? If so, we can fix this by adding lodash as a peer dependency in `package.json`.

**Comment by clarencecastillo** [comment]
> ```js
>     async getArtworks(
>         filters: QueryFilter[] = [],
>         limit: number = 10,
>         orderBy: ArtworksOrderKey = 'title',
>         direction: firebase.firestore.OrderByDirection = 'asc'
>     ): Promise<Artwork[]> {
>         const orderByPath = ARTWORKS_ORDER_KEY_PATH_MAP[orderBy];
>         const results = await buildQuery(this.artworks, limit, orderByPath, direction, filters).get();
>         return Promise.all(results.docs.map(doc => this.toArtwork(withId<FirebaseArtwork>(doc.data(), doc.id))));
>     }
> 
>     async getArtwork(id: string): Promise<Artwork> {
>         const ref = this.artworks.doc(id);
>         const doc = await ref.get();
>         return this.toArtwork(withId<FirebaseArtwork>(doc.data(), id));
>     }
> 
>     private async toArtwork(data: FirebaseArtwork): Promise<Artwork> {
>         const artist = this.peopleRepository.getPerson(data.artist.id);
>         return _.assign(data, {
>             artist: await artist
>         });
>     }
> ```
> 
> Here is the issue, when using `toArtwork` the value of `data` is a string (or reference). It's not an object and does not have `id` field.
> Hence, when fetching data from artworks there are runtime error saying `Uncaught (in promise) TypeError: Cannot read property 'getPerson' of undefined`
> Same error would expected to happen in eventRepo

The purpose of `toArtwork` is to map Firebase's Artwork object as defined in `artwork.firebase.ts` into our own definition of Artwork. It resolves the `artist` attribute from a reference into an actual object using `PeopleRepository`. This also means that the expected value of `data` is an object and it should have the `id` field and if not, then the problem lies in the caller.

As for the other error, I think it is a different issue altogether. If the error says `TypeError: Cannot read property 'getPerson' of undefined`, then does it not mean `peopleRepository` is not set up correctly? Might want to check if an instance of it is passed in the constructor.

**Comment by ZaynJarvis** [comment]
> ```shell
> > ```shell
> > artworks.repository.js:157 Uncaught (in promise) TypeError: Cannot read property 'assign' of undefined
> >     at ArtworksRepository.<anonymous> (artworks.repository.js:157)
> >     at step (tslib.es6.js:197)
> >     at Object.next (tslib.es6.js:127)
> >     at tslib.es6.js:100
> >     at new Promise (<anonymous>)
> >     at Module.__awaiter (tslib.es6.js:77)
> >     at ArtworksRepository.toArtwork (artworks.repository.js:150)
> >     at artworks.repository.js:121
> >     at Array.map (<anonymous>)
> >     at ArtworksRepository.<anonymous> (artworks.repository.js:120)
> >     at step (tslib.es6.js:197)
> >     at Object.next (tslib.es6.js:127)
> >     at fulfilled (tslib.es6.js:80)
> > ```
> 
> 
> Is it not because you don't have lodash installed? If so, we can fix this by adding lodash as a peer dependency in `package.json`.
> ```

I don’t think this is the issue. Since people .org and loc repo works fine.

**Comment by ZaynJarvis** [comment]
I’m not able to reproduce the same issue now. It may be the issue on constructor field. Since I didn’t find functional differences between the first commit.

**Comment by ZaynJarvis** [comment]
Will setup a new branch to test on this package.
