### ISSUE TITLE
Object speading over lodash

### ISSUE THREAD

**Issue by ZaynJarvis** [ntuoss/hackoss#16]
Shall we change some syntax of lodash to js speading syntax `{...data, override}`
It surely reduce a large amount of boilerplate code and is there a way to maintain the ts type benefit at the same time with optional fields?

**Comment by clarencecastillo** [comment]
Closing in favour of the proposed fix in #15. See https://github.com/ntuoss/hackoss/pull/15#discussion_r255544049
